# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 570)
        MainWindow.setMinimumSize(QtCore.QSize(400, 570))
        MainWindow.setMaximumSize(QtCore.QSize(400, 570))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 343, 487))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.list_students = QtWidgets.QListWidget(parent=self.layoutWidget)
        self.list_students.setObjectName("list_students")
        self.gridLayout_2.addWidget(self.list_students, 1, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_add = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button_add.setObjectName("button_add")
        self.gridLayout.addWidget(self.button_add, 0, 0, 1, 1)
        self.button_rem = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button_rem.setObjectName("button_rem")
        self.gridLayout.addWidget(self.button_rem, 1, 0, 1, 1)
        self.button_edit = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button_edit.setObjectName("button_edit")
        self.gridLayout.addWidget(self.button_edit, 2, 0, 1, 1)
        self.button_sum = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button_sum.setObjectName("button_sum")
        self.gridLayout.addWidget(self.button_sum, 5, 0, 1, 1)
        self.button_clear = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button_clear.setObjectName("button_clear")
        self.gridLayout.addWidget(self.button_clear, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_summary = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_summary.setFont(font)
        self.label_summary.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_summary.setObjectName("label_summary")
        self.verticalLayout.addWidget(self.label_summary)
        self.list_summary = QtWidgets.QListWidget(parent=self.layoutWidget)
        self.list_summary.setObjectName("list_summary")
        self.verticalLayout.addWidget(self.list_summary)
        self.button_open_csv = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button_open_csv.setObjectName("button_open_csv")
        self.verticalLayout.addWidget(self.button_open_csv)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student Grade Manager"))
        self.label_title.setText(_translate("MainWindow", " Student List"))
        self.button_add.setText(_translate("MainWindow", "Add"))
        self.button_rem.setText(_translate("MainWindow", "Remove"))
        self.button_edit.setText(_translate("MainWindow", "Edit"))
        self.button_sum.setText(_translate("MainWindow", "Summary"))
        self.button_clear.setText(_translate("MainWindow", "Clear"))
        self.label_summary.setText(_translate("MainWindow", "Summary"))
        self.button_open_csv.setText(_translate("MainWindow", "Open CSV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
